#+TITLE: RAMBO on diet in Fortran 2008
#+AUTHOR: Simon Braß
#+E-MAIL: brass@physik.uni-siegen.de

#+LATEX_COMPILER: lualatex
#+LATEX_HEADER: \usepackage[margin=2.5cm]{geometry}

* Explanation

  The n-body phase-space measure[fn:1] for total momentum $Q^2$ is given by,
  \begin{equation}
  \mathup{d}Φ_n \left(p_1, \dots, p_n; Q\right) = \frac{1}{(2π)^{3n}} δ\left( \sum_{i = 1}^{n} p_n - Q \right) \prod_{i = 1}^{n} \mathup{d}⁴p_i δ\left( p_i² - m_i² \right) Θ\left( p_i⁰ - m_i \right).
  \end{equation}
  Each particle with momentum $p_i$ satisfies the on-shell condition $m_i² = p_i²$.
  We decompose the phase space with iterative $1 → 2$ decays, such that, we have a parent system $Q_{i - 1}$ decaying into a child system $Q_i$ and a particle $p_i$, explicitly,
  \begin{equation}
  Q_{i - 1} = Q_i + p_{i - 1} \text{ and } M_{i}² = Q_i².
  \end{equation}
  We start the decomposition with $Q_1 = Q$ and identify $Q_n = p_n$, which leaves us with $(n - 2)$ intermediate masses $M_i$ and $(n - 1)$ independent mass systems.
  We can then rewrite the n-body phase-space measure
  \begin{equation}
    \mathup{d}Φₙ = \left( \prod_{i = 2}^{n} \mathup{d}Φ₂ (p_{i - 1}, Q_i; Q_{i - 1}) \right)
    \left( \prod_{i = 2}^{n - 1} θ(M_{i - 1}- m_{i - 1} - M_{i}) θ\left( M_i -
        \sum_{k = i}^{n} m_k \right) \mathup{d}M_i²\right).
  \end{equation}
  We boost into the rest frame of the parent system $Q_{i - 1}$ by applying
  \begin{equation}
    Λ_{μ}(Q_{i - 1}) = \begin{pmatrix}
      γ & -γ \vec{β} \\
      -γ \vec{β} & \vec{1} + (γ - 1)\frac{\langle \vec{b}, \cdot \rangle}{\langle \vec{b}, \vec{b}\rangle} \vec{b},
    \end{pmatrix}
  \end{equation}
  where $\vec{β} = \vec{Q}_{i - 1} / Q⁰_{i - 1}$ and $γ = 1 / \sqrt{1 - β²}$.
  We have the child system $Q_{i}$ and the particle $p_{i - 1}$ in the rest frame given as
  \begin{align}
    \tilde Q_{i - 1} & = \tilde Q_{i} + \tilde p_{i - 1} = (M_{i - 1}, \vec 0),  \\
    \tilde{Q}_{i}    & = \left(\sqrt{M_{i}² + \vec{\tilde{Q_i}}²}, -\vec{\tilde{p}}\right), \\
    \tilde{p}_{i - 1}& = \left(\sqrt{m_{i - 1}² + \vec{\tilde{p}}_{i - 1}²}, \vec{\tilde{p}}\right).
  \end{align}
  We parametrize the three-momentum vector with two parameters $θ_{i - 1}, φ_{i - 1}$, respectively,
  \begin{equation}
  \vec{\tilde{p}} = 4M_{i - 1} ρ(M_{i - 1}, M_{i}, m_{i - 1}) (\cos φ_{i - 1}\sin θ_{i - 1}, \sin φ_{i - 1} \sin θ_{i - 1}, \cos θ_{i - 1}),
  \end{equation}
  with $\rho (M_{i - 1}, M_{i}, m_{i - 1}) = \sqrt{(M_{i - 1}² - (M_{i} - m_{i +  1})²)(M_{i - 1}² - (M_{i} - m_{i -  1})²)} / (8M_{i - 1}²)$.
  The two-body phase-space is then given by
  \begin{equation}
  \mathup{d}Φ₂ (p_{i - 1}, Q_{i}; Q_{i - 1}) = ρ(M_{i - 1}, M_{i}, m_{i - 1})\mathup{d}\!\cos θ_{i - 1}\mathup{d}φ_{i - 1}.
  \end{equation}
  We have for the intermediate mass measure
  \begin{multline}
    \mathup{d}Mₙ= \\
    \left(\prod_{i = 2}^{n - 1} ρ (M_{i - 1}, M_{i}, m_{i - 1}) θ(M_{i
        - 1}- m_{i - 1} - M_{i})θ\left( M_i - \sum_{k = i}^{n} m_k \right) \mathup{d}
      M_i^2\right) ρ(M_{n - 1}, m_n, m_{n - 1}).
  \end{multline}
  All in all, we have $(n - 2)$ intermediate mass parameters and $(2n - 2)$ angle parameters[fn::We have $n - 1$ systems, leaving us with $2(n - 1)$ independent angles.], reproducing the $3n - 4$ degress of freedom of the phase-space.

** Massless case

   We express the mass measur[fn:3]e for $m_i = 0; ∀i$
   \begin{equation}
   \mathup{d}M_n(0) = \frac{1}{8^{n - 1}} \prod_{i = 2}^{n - 1} \frac{M_{i - 1}^2 - M_{i}^2}{M_{i - 1}^2} θ(M_{i - 1}^2 - M_i^2)θ(M_i^2)\mathup{d}M_i^2.
   \end{equation}
   We use the phase-space cascading (and the conditions $θ(M_{i - 1}^2 - M_i^2)$ and $Θ(M_i^2)$) to parametrize the $M_i$ with the parameters $u_i ∈ (0, 1)$ in dependence of $M₁ = \sqrt{Q²}$ by
   \begin{equation}
   \label{eq:random_masses}
   M_i^2 = u_2 \cdots u_i M_1^2.
   \end{equation}
   We substitute $u_i = \frac{M_i^2}{M_{i - 1}^2}$ with $\mathup{d}M_i^2 = M_{i - 1}^2\mathup{d}M_i^2$, where we take $M_{i - 1}^2 = u_2 \cdots u_{i - 1} M_1^2$ and get for each i-th term a factor of $u^{n - 1 - i}$.
   We arrive at the expression
   \begin{equation}
    \mathup{d}M_n(0) = \frac{1}{8^{n - 1}} M_{1}^{2(n - 2)} \prod_{i = 2}^{n - 1} u_i^{n - 1 - i} (1 - u_i)θ(1 - u_i)θ(u_i)\mathup{d}u_i.
   \end{equation}
   With the substitution $v_i = (n + 1 - i)u_i^{n + 1 - i} - (n - i)u_i^{n - i}$ and $\frac{\mathup{d}v_i}{\mathup{d}u_i} = (n + 1 - i)(n - i) (u_i^{n + 1 - i} - u_i^{n - i})$ we have
   \begin{equation}
    \mathup{d}M_n(0) = \frac{1}{8^{n - 1}} M_{1}^{2(n - 2)} \prod_{k = 2}^{n - 1} \frac{1}{n + 1 - k} \prod_{l = 2}^{n - 1} \frac{1}{n - l} \prod_{i = 2}^{n - 1} θ(1 - v_i)θ(v_i)\mathup{d}v_i,
   \end{equation}
   where the products over $k, l$ reduce to $\frac{1}{(n - 1)!(n - 2)!}$.

   We connect with the last substitution an integral over the limits $(0, 1)$ with the intermediate masses.
   Sampling with $(n -2)$ random numbers $r_i$ we solve for $u_i$
   \begin{equation}
   \label{eq:solve_for_u}
   r_i = (n + 1 - i)u_i^{n + 1 - i} - (n - i)u_i^{n - i},
   \end{equation}
   and get the intermediates masses $M_i$ with [[ref:eq:random_masses]].

** Massive case

   We rewrite the measure for the intermediate masses for massive particles with $K_i = M_i - \sum_{k = i}^{n} m_k, i = 1, \dots, n - 1$, $K_n = 0$ and $\mathup{d}K_i^2 = \frac{K_i}{M_i} \mathup{d}M_i^2$
   \begin{equation}
   \label{eq:reweighting-factor}
   \mathup{d}M_n = \frac{1}{8} \prod_{i = 2}^{n} \frac{ρ(M_{i - 1}, M_i, m_{i - 1})}{ρ(K_{i - 1}, K_i, 0)} \prod_{i = 2}^{n - 1} \frac{M_i}{K_i} \mathup{d} M_n(0).
   \end{equation}
   We can use the /massless/ algorithm with an appropriate reweighting factor.

** Phasespace volume

   The phasespace volume for the massless case is given by
   \begin{equation}
   V_n = \int \! \mathup{d}Φ_n(p_1, \dots, p_n; Q) = \frac{1}{(2π)^{3n}} \left( \frac{π}{2} \right)^{n - 1} \frac{(Q²)^{n - 2}}{(n - 1)!(n - 2)!}.
   \end{equation}
   The weight for the massless case is[fn:2]
   \begin{equation}
   \mathup{d}V_n(0) = \frac{1}{8^{n - 1}(2π)^{3n}} \frac{(Q²)^{n - 2}}{(n - 1)!(n - 2)!} \left( \prod_{i = 2}^{n - 1} \mathup{d}u_i \right) \left(\mathup{d} Ω₂\right)^{n - 1} = V_n(0)\, \mathup{d}^{3n - 4} x,\, x ∈ (0, 1)^{\otimes 3n - 4}.
   \end{equation}
   We apply the reweighting factor for the massive case
   \begin{equation}
   dV_n = \prod_{i = 2}^{n} \frac{ρ(M_{i - 1}, M_i, m_{i - 1})}{ρ(K_{i - 1}, K_i, 0)} \prod_{i = 2}^{n - 1} \frac{M_i}{K_i} \mathup{d}V_n(0).
   \end{equation}
   We note that in the implementation of the factor of $ρ(M_{n - 1}, m_{n}, m_{n - 1}) / ρ(K_{n - 1}, 0, 0)$ reduces to
   \begin{equation}
    \frac{ρ(M_{n - 1}, m_{n}, m_{n - 1})}{ρ(K_{n - 1}, 0, 0)} = 8 ρ(M_{n - 1}, m_{n}, m_{n - 1}),
   \end{equation}
   justifying the additional factor of $\frac{1}{8}$.
   We have precomputed the factors for massive phasespace weight, see table [[tab:prefactors]].
   #+CAPTION: Weights for the massless phasespace.
   #+NAME: tab:prefactors
   #+ATTR_LATEX: :booktabs t
|  n | $\mathup{d}V_n (0) / (Q²)^{n - 2}$ |
|----+------------------------------------|
|  2 |                   2.5394567219E-07 |
|  3 |                   6.3985449928E-11 |
|  4 |                   5.3740337021E-15 |
|  5 |                   2.2567816795E-19 |
|  6 |                   5.6863025035E-24 |
|  7 |                   9.5516656766E-29 |
|  8 |                   1.1460411996E-33 |
|  9 |                   1.0312942860E-38 |
| 10 |                   7.2180605853E-44 |
|----+------------------------------------|

** The "reduced" RAMBO algorithm

   We rewrite the algorithm given in the original notes directly for the massive case.
   In order to solve [[ref:eq:solve_for_u]] we use Newton's method as we can provide the derivative /a-priori/,
   \begin{align}
   f(x; n, i)  & = (n + 1 - i)x^{n - i} - (n - i)x^{n + 1 - i},\\
   f'(x; n, i) & = (n + 1 - i)(n - i)x^{n - i - 1} - (n - i)(n - i - 1)x^{n - i},\\
   x_n         & = x_{n - 1} + \frac{f(x; n, i)}{f'(x; n, i)}.
   \end{align}
   1. Calculate $K_1 = \sqrt{Q^2} - \sum_{k = 1}^{n} m_k$ and solve for $K_i; n > i ≥ 2$.
   2. Determine $M_i = K_i + \sum_{k = i}^{n} m_k$ (with $M_n = 0$) and the reweighting factor in [[ref:eq:reweighting-factor]].
   3. Loop over the intermediate mass systems and calculate $p_i, Q_i$:
      - $\cos θ_i = 2 r_{n - 5 + 2i} - 1$ and $φ_i = 2π r_{n - 2 + 2i}$,
      - $\tilde{p} = 4 M_{i - 1} ρ(M_{i - 1}, M_i, 0)$,
      - boost from the rest frame of $Q_{i - 1}$ to c.m.s./lab-frame.
   4. Compute the overall weight

** Lorentz-invariant flux

   The Lorentz-invariant flux $F$ can be written with $s = (p_a + p_b)^2$ and $m_i^2 = p_i^2$ as
   \begin{equation}
     F = 4 \sqrt{\left( p_a \cdot p_b\right)² - m_a^2 m_b^2} = 2 \sqrt{λ(s, m_a^2, m_b^2)},
   \end{equation}
   where we used the identity $(s - m_a^2 - m_b^2)^2 = λ(s, m_a^2, m_b^2) - 4m_a^2 m_b^2$.
   The differential cross section is then given by
   \begin{equation}
   \mathup{d}σ = \frac{(2π)^4}{2\sqrt{λ(s, m_a^2, m_b^2)}} \left| \mathscr{M}_{fi} \right|^2 \, \mathup{d}Π_{\text{LIPS}}.
   \end{equation}
* Implementation

** Two-body phasespace

   For the case of a two-body phasespace, the intermediate masses are fixed by the overall momenta and a onshell mass.
   \begin{align}
     Q₁ = Q\\
     Q₂ = p₂
   \end{align}
   We use the random numbers for the angles between the two final state particles.

** Root-finding algorithm


   Different algorithms for root-finding exist with different properties such as: convergence rate and failure possibility.
   We select an algorithm that always finds a root in a given interval, in our case $(0, 1)$.
   Therefore, we choose the bisect method as it guarantees to converge to a root given that the function has at least one sign-change inside the given search interval.
   Another advantage is that the root lies always in the search interval which is not necessarily the case for other methods, like Newton's method.

* Footnotes

[fn:3] We point out the additional factor of $ρ(M_{n - 1}, 0, 0) = \frac{1}{8}$.

[fn:2] We integrate over $(n -1)$ -independent solid angles, $\left(\int \mathup{d}Ω₂\right)^{n - 1} = (4π)^{n - 1}\,\mathup{d}^{2n - 2}x$.

[fn:1] We take definition from Review of Particle Physics, we take care of the factor $(2π)⁴$ from the normalization of the four-momentum conserving $δ$ distribution in the flux factor of the cross section.
