#!/usr/bin/env python2

Import('env')

rambo = env.SharedLibrary("rambo", Glob("*.f90"))

# Static build for profiler.
# rambo = env.Library("rambo", Glob("*.f90"))

env.Install("$PREFIX/lib", "mod/phs_rambo.mod")
env.Install("$PREFIX/lib", rambo)

Export('rambo')
